### PR TITLE
Use kotlin dsl and upgrade deps.

### PR DESCRIPTION
**Pull request by Globegitter**
Took me a while to figure out so I thought it would be worth upstreaming. Probably makes sense to put on its own branch though. Let me know what you think

### CODE REVIEW

**Comment by marcoferrer** [comment]
Thanks for the submission. I think you're right about putting it in a separate branch. Ill push a new branch so this can be merged into it. When its up, would you be able to reopen the PR to that branch?

**Comment by Globegitter** [comment]
Yep that sounds good to me.

**Comment by Globegitter** [comment]
@marcoferrer any update on creating the new branch?

**Comment by marcoferrer** [comment]
Sorry about that. The new branch is up at `protobuf-lite-kt-dsl`

**Comment by Globegitter** [comment]
@marcoferrer thanks the PR is now ready

**Review by marcoferrer — APPROVED** [review]

**Comment by marcoferrer** [comment]
Thanks again!

**Pull request merged**
